/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package edu.usta.forms;

import edu.usta.classes.*;
import edu.usta.utils.Information;
import java.util.List;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cpaez
 */
public class FormPrincipal extends javax.swing.JPanel {

    // Definición de variables personalizadas
    private List<Product> arrProducts = new ArrayList<>();
    private Brand[] arrBrands;

    // Definición de modelos por defecto para Table y ComboBox
    private String[] columnNames = {"#", "Nombre", "Marca", "Value", "Cantidad"};
    private DefaultTableModel tableModel = new DefaultTableModel(columnNames, 0);
    private DefaultComboBoxModel comboBoxModel = new DefaultComboBoxModel();

    /**
     * Creates new form FormPrincipal
     */
    public FormPrincipal() {
        initComponents();
        arrBrands = Information.generateBrands();

        tbtProducts.setModel(tableModel);
        cbxBrand.setModel(comboBoxModel);

        fillComboBox();
        fillTable();
        cleanInputs();
    }

    /**
     * La función `fillComboBox` llena un combo box con los nombres de las
     * marcas de un array.
     */
    private void fillComboBox() {
        int amount = arrBrands.length;
        comboBoxModel.addElement("Seleccione una marca");
        for (int i = 0; i < amount; i++) {
            comboBoxModel.addElement(arrBrands[i].getName());
        }
    }

    /**
     * La función `fillTable` limpia el modelo de la tabla y lo llena con datos
     * de un array de productos.
     */
    private void fillTable() {
        tableModel.setRowCount(0);

        for (Product product : arrProducts) {
            // Cada fila tiene 5 posiciones para los atributos del producto
            Object[] row = new Object[5];
            row[0] = product.getCod();
            row[1] = product.getName();
            row[2] = product.getBrand().getName();
            row[3] = product.getValue();
            row[4] = product.getAmount();
            // Añade la fila correspondiente dentro de la tabla
            tableModel.addRow(row);
        }
    }

    /**
     * La función `closeWindow` muestra un diálogo de confirmación y cierra la
     * aplicación si el usuario elige "Aceptar" (Sí).
     */
    private void closeWindow() {
        String[] buttonTexts = {"Aceptar", "Cancelar"};

        int option = JOptionPane.showOptionDialog(
                panelContent, // Panel donde se mostrá el mensaje
                "¿Está seguro de salir de la aplicación?", // Mensaje a mostrar
                "Salir", // Título del mensaje
                JOptionPane.YES_NO_CANCEL_OPTION, // Cantidad de Opciones
                JOptionPane.INFORMATION_MESSAGE, // Tipo de mensaje
                null, // Icono
                buttonTexts, // Texto a mostrar en los botones
                buttonTexts[1] // Opción enfocada por defecto
        );

        if (option == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }

    /**
     * La función `cleanInputs` limpia los campos del formulario
     */
    private void cleanInputs() {
        // Marcar la opción de "Seleccione una marca"
        cbxBrand.setSelectedIndex(0);
        // Limpiar las cajas de texto y dejar un mensaje
        inputName.setText("Ingrese un nombre");
        inputValue.setText("Ingrese un valor");
        inputAmount.setText("Ingrese una cantidad");
        // Enfocar el input del nombre
        inputName.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        panelHeader = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        panelContent = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbtProducts = new javax.swing.JTable();
        panelForm = new javax.swing.JPanel();
        panelName = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        inputName = new javax.swing.JTextField();
        panelBrand = new javax.swing.JPanel();
        lblBrand = new javax.swing.JLabel();
        cbxBrand = new javax.swing.JComboBox<>();
        panelAmount = new javax.swing.JPanel();
        lblAmount = new javax.swing.JLabel();
        inputAmount = new javax.swing.JTextField();
        panelValue = new javax.swing.JPanel();
        lblValue = new javax.swing.JLabel();
        inputValue = new javax.swing.JTextField();
        btnRegister = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        panelHeader.setBackground(new java.awt.Color(102, 204, 255));
        panelHeader.setPreferredSize(new java.awt.Dimension(500, 50));
        panelHeader.setRequestFocusEnabled(false);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Productos");

        btnClose.setBackground(new java.awt.Color(255, 0, 0));
        btnClose.setForeground(new java.awt.Color(255, 255, 255));
        btnClose.setText("X");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 647, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnClose)
                .addContainerGap())
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnClose))
        );

        tbtProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbtProducts);

        panelForm.setBackground(new java.awt.Color(204, 204, 204));

        lblName.setText("Nombre");

        inputName.setText("jTextField1");

        javax.swing.GroupLayout panelNameLayout = new javax.swing.GroupLayout(panelName);
        panelName.setLayout(panelNameLayout);
        panelNameLayout.setHorizontalGroup(
            panelNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputName)
                    .addGroup(panelNameLayout.createSequentialGroup()
                        .addComponent(lblName)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelNameLayout.setVerticalGroup(
            panelNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputName, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblBrand.setText("Marca");

        cbxBrand.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout panelBrandLayout = new javax.swing.GroupLayout(panelBrand);
        panelBrand.setLayout(panelBrandLayout);
        panelBrandLayout.setHorizontalGroup(
            panelBrandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBrandLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBrandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxBrand, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelBrandLayout.createSequentialGroup()
                        .addComponent(lblBrand)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelBrandLayout.setVerticalGroup(
            panelBrandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBrandLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBrand)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbxBrand, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblAmount.setText("Cantidad");

        inputAmount.setText("jTextField1");

        javax.swing.GroupLayout panelAmountLayout = new javax.swing.GroupLayout(panelAmount);
        panelAmount.setLayout(panelAmountLayout);
        panelAmountLayout.setHorizontalGroup(
            panelAmountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAmountLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAmountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputAmount)
                    .addGroup(panelAmountLayout.createSequentialGroup()
                        .addComponent(lblAmount)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelAmountLayout.setVerticalGroup(
            panelAmountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAmountLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAmount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputAmount, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblValue.setText("Valor");

        inputValue.setText("jTextField1");

        javax.swing.GroupLayout panelValueLayout = new javax.swing.GroupLayout(panelValue);
        panelValue.setLayout(panelValueLayout);
        panelValueLayout.setHorizontalGroup(
            panelValueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelValueLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelValueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputValue)
                    .addGroup(panelValueLayout.createSequentialGroup()
                        .addComponent(lblValue)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelValueLayout.setVerticalGroup(
            panelValueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelValueLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblValue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputValue, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnRegister.setForeground(new java.awt.Color(0, 204, 102));
        btnRegister.setText("Registrar");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        btnCancel.setForeground(new java.awt.Color(204, 0, 51));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFormLayout = new javax.swing.GroupLayout(panelForm);
        panelForm.setLayout(panelFormLayout);
        panelFormLayout.setHorizontalGroup(
            panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelBrand, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelFormLayout.createSequentialGroup()
                        .addComponent(btnRegister)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancel)))
                .addContainerGap())
        );
        panelFormLayout.setVerticalGroup(
            panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(panelBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegister)
                    .addComponent(btnCancel))
                .addGap(70, 70, 70))
        );

        javax.swing.GroupLayout panelContentLayout = new javax.swing.GroupLayout(panelContent);
        panelContent.setLayout(panelContentLayout);
        panelContentLayout.setHorizontalGroup(
            panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContentLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelContentLayout.setVerticalGroup(
            panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(panelForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
                    .addComponent(panelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        cleanInputs();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnRegisterActionPerformed
        String name, value, amount;
        int amountProduct, brandSelected, cod = 0;
        double valueProduct = 0;

        brandSelected = cbxBrand.getSelectedIndex();

        name = inputName.getText();
        value = inputValue.getText();
        amount = inputAmount.getText();
        cod = arrProducts.size() + 1;

        if (brandSelected != 0) {
            if (name.isEmpty() || value.isEmpty() || amount.isEmpty()) {
                JOptionPane.showMessageDialog(
                        panelPrincipal,
                        "Faltan datos por llenar",
                        "Advertencia",
                        JOptionPane.WARNING_MESSAGE);
            } else {
                try {
                    amountProduct = Integer.parseInt(amount);
                    valueProduct = Double.parseDouble(value);

                    Product newProduct = new Product(
                            cod, name,
                            arrBrands[brandSelected - 1],
                            valueProduct,
                            amountProduct
                    );

                    arrProducts.add(newProduct);

                    fillTable();
                    cleanInputs();
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(
                            panelPrincipal,
                            "El Valor y la Cantidad deben ser númericos",
                            "Advertencia",
                            JOptionPane.WARNING_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(
                    panelPrincipal, // Panel donde se mostrará
                    "Seleccione una Marca", // Mensaje a mostrar
                    "Advertencia", // Titulo del panel
                    JOptionPane.WARNING_MESSAGE // Tipo de alerta
            );
        }
    }// GEN-LAST:event_btnRegisterActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCloseActionPerformed
        closeWindow();
    }// GEN-LAST:event_btnCloseActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnRegister;
    private javax.swing.JComboBox<String> cbxBrand;
    private javax.swing.JTextField inputAmount;
    private javax.swing.JTextField inputName;
    private javax.swing.JTextField inputValue;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAmount;
    private javax.swing.JLabel lblBrand;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblValue;
    private javax.swing.JPanel panelAmount;
    private javax.swing.JPanel panelBrand;
    private javax.swing.JPanel panelContent;
    private javax.swing.JPanel panelForm;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelName;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelValue;
    private javax.swing.JTable tbtProducts;
    // End of variables declaration//GEN-END:variables
}
